name: CI/CD for React + Flask

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # services:
      # postgres:
      #   image: postgres:latest
      #   ports:
      #     - 5432:5432
      #   env:
      #     POSTGRES_DB: plantric
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: Arth1827
      #   options: >-
      #     --health-cmd="pg_isready"
      #     --health-interval=10s
      #     --health-timeout=5s
      #     --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend/plantric_app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: echo "No test yet!"

      # Set up Node.js and React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # - name: Run frontend tests
      #   run: |
      #     cd frontend
      #     npm test -- --watchAll=false

      - name: Build frontend
        run: |
          cd frontend
          npm build

      # Optional: Deploy step (can be added for Netlify, Vercel, or Heroku)
